SecurityError: Failed to set a named property 'href' on 'Location': The current window does not have permission to navigate the target frame to 'https://checkout.stripe.com/c/pay/cs_test_a1mOYO7JGTSZ0tTJTTrQ55U016IWQtXuYgBAQ4xAXEFnXrO2wzqHWHOHRP#fidkdWxOYHwnPyd1blpxYHZxWjA0V05cd25XXWgzfWtAR0Z1fUFmUm5zakJUSl9mcWpxdkhpdzNUSzZXUGxcM2E9THdOcFwybDN9ak9kbkZxXGFDb3RdQDA3NHFOc2JIcVNvZFxsZ0BrMm5qNTVsU2diaW0xSicpJ2hsYXYnP34nYnBsYSc%2FJ2MwMjxgYz0xKDAwYWQoMWc3ZihkZ2NkKDU8Zzw1MWZgMzQ1MmYzNz03YScpJ2hwbGEnPyczMDcxMmA0MSg0MT0wKDFhZzwoPGRjNCgzNzU2MmAxYWc0NTUwYzJgMzAnKSd2bGEnPycxZGAxZ2dkZyhjPGYyKDFgZmQoZDJmPSg9Mmc0PGZhZmE0M2Y0MjdjMmMneCknZ2BxZHYnP15YKSdpZHxqcHFRfHVgJz8ndmxrYmlgWmxxYGgnKSd3YGNgd3dgd0p3bGJsayc%2FJ21xcXV2PyoqMzU1NShsYX0odnFwYWxqKDQyMTM3MT0xNTUxMjMrZmlwdnFgdyhpM3NuYXVgd3QwYGdkdGo2dHwxbnZzanRqaCtmaWpwYXJqd252cWRxbGprdithYHMneCUl'.     at new Promise (<anonymous>)     at o (https://js.stripe.com/v3:1:66543)     at vd (https://js.stripe.com/v3:1:481714)     at https://js.stripe.com/v3:1:577537     at async handleContinueToPayment (https://6000-idx-studio-1746248400476.cluster-l6vkdperq5ebaqo3qy4ksvoqom.cloudworkstations.dev/_next/static/chunks/src_bf5ba062._.js:1550:31)